[[libaom]]
arch = "aarch64"
git-tree-sha1 = "8aeda74365ddd4a5b4b857356622b5c7612a3f2e"
os = "macos"

    [[libaom.download]]
    sha256 = "da792db5fbfb9a1f3b7ad8982c518b32c98cbc9619fb30718120a2dbc1b2f658"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.aarch64-apple-darwin.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f891200a6d253b5f88d99e7005cc8e82aa317b3b"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "2068bb05ddd5f1dd8a6e18d9d1e0159f3bdb67bd8c56318a828016e8f74d1697"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70c22586759ed4c210a0f2434c50958aad2825d1"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "0273e20716de86fe4c29bc2097ed0538999b5350ab735f09d4a7ebab017b4045"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "545806995d512eff8dee85d18d680546d097c311"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "0a1b590b852786bea9c51b934d916ff3e43bdf4728335c5a9e0adbcf010a0009"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "676e52a86aba331044c3a4dcffd444ee0bbc251b"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "aba654d5c9e0e73ba618ba73dfd4123dce1e9fc1b9d79d8af8bcaefbabd0f48b"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b516cdeadcea66e5c41c23548a9419831349fcc"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "a6eafdea84bcff7a35804cb7af38ff6ba77467e02531802288df0ec77d87ac99"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ed5a8f9af8a0ccbaa84eab609603717ce670acf"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "a1a88482b4904e946a22cfa829804e569dea568cb580999eb4eaf910e0a74f2b"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f53f0e731a338627545757d55c65031613661ec9"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "241f0e10f64f990b743a39fb78622cacaf683f1c2710fe3eca8bcccff39e5d81"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45ef158512ec70ccdaa80d4a2b3e00f2a3bb1523"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "024b50e9d5f52d3b21de243db39d99b74872887a6dae5b12c4d145dbe2e4b05e"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b853ce8dff14b18d8df4a4e15d959666690188d9"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "460215a96ee69450488f4163b802135a37534aa97ad47bd5c0d0a21861aba608"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f7ba8e81e83d6b8e424b93b59cce9f9a435d3ef"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "f0c100b42c8e90e8b9c52bc90c572dd6981dfc8930498ef376622ff9cae6734a"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81fe7e55cf0d5a81cc37be2cd9c2bb93ec07eb8e"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "69fdfc57e47e7fadb5ba1590e56767aa79ca5aecf553599d221cd5c71adf7002"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fb764f7afe1bc6dc2006497d43e7417a9ff57b4e"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "08996dfe6854a94f3ff552e37c0de5c9921c0a3b22aa7fd6a534cc042898335f"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d28cedacbc1ab67fa24e6f92cc403e96fac199f9"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "973e4e9c496bcf6d09059729d6eca532cbaabde3070d8169b34e64720cc0a4a7"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-linux-gnu-cxx03.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14b68a3e7035e708f71090c10df666567351b07d"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "c43188cf20968b43e3c9d9abfb862b921d1738e9c3f9e2e7aa5f197ec92bfe8a"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e70ef6d230bbacf5f32ac16050b999ec91d251c"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "83d8f3bf375eaca6427244c74fb2b1405312923dcc2ce4b1db20c5a5fbc59da2"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-linux-musl-cxx03.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2edabb6abe6cb413acd66585f4f61361e0243c0e"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "d3f611d86ba5091e45bbb7a0741d95c7ae44e67a45550733bb5bb6c2a48419ef"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "973d1260d0b8182245a37ea570bd60c6bf884628"
os = "windows"

    [[libaom.download]]
    sha256 = "b3d95bfc70307a8d6103bd75c164b71f2f516416289b9ccb6c62554b412ea96f"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f16b37a453a14bb033e3c7c80e17d4796baa1e23"
os = "windows"

    [[libaom.download]]
    sha256 = "06a348048dab2f9ecee2a09949fc8656df3a2b9a346d2ff2a67a7878f9e02c63"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[libaom]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "340a25db553681ab95436ee621c0fc4e0d29a29a"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "505c5a077470e59c8ce02052b3292663703fd78090b5ebc852d384eccdd38cda"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libaom]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d27a06e418b3bd60d40b5db174d192c500400c25"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "6c934930e91750331c3af57e691e545338df1cf0d354ecb3550961e6b9123e63"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
git-tree-sha1 = "ea0d780d1d257836385747da7db21967d7450bdc"
os = "macos"

    [[libaom.download]]
    sha256 = "7545cd44c1c6f4ff5599a20831b3c569541fbafee8cc04c33433f766a78840d4"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-apple-darwin.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e63a5ea0e16a5b64d2baa107c89ed916b210cef"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "5408619c9bb4f650bd65d5f9d95514b7958debe582865e1c924d8f6416b80f76"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1cf7375e8ec1bbe1219934488737c12237ba2012"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "d9412c2cbd779d203cc4daf2532a1da13c2ca3a962c411219e6b59a3c97bbec1"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c34ca1c950e7c091a99a1f7b6392889d463458fb"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "185b6c171775c787c336c0d3615543ab1af9813a273c083f3f66fff513368dec"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb0ce10c840c29f025b2195e325e6ccce0f27b7a"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "13005ed6202f08e1d05a8751d36ea99a9a5158b8b515b437226f64691acccf90"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
git-tree-sha1 = "8bcf93054d1a009ad7d0df92ec9554c15e4072af"
os = "freebsd"

    [[libaom.download]]
    sha256 = "dec3350e02dd5cf3497d0392b1f26df8b73e77981a02ed3f07fb31ee609f9a61"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-unknown-freebsd.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b22a16a5432a9c4d7a4dd628f919904514980c81"
os = "windows"

    [[libaom.download]]
    sha256 = "7fedf196417a06471e5b48104febb10bb8006c21d20c699b8f7b38017d055d8c"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0750898c47cd86188d0a9fb7ca8ddf13967cc1b8"
os = "windows"

    [[libaom.download]]
    sha256 = "4bce9a90d25367835eeeac39e97faedbf84ef6137d1f924ed54123da287605c1"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.9.0+0/libaom.v3.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
