[[libaom]]
arch = "aarch64"
git-tree-sha1 = "0f7add55a4e028ca1b0b729cf2eb313566d3ebce"
os = "macos"

    [[libaom.download]]
    sha256 = "e1327fb2200ccfde42938be11919313a9c40221c072f97b61f96aa3e3e54f3c1"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.aarch64-apple-darwin.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88d9d202f2e367952d2021eaea47425165b6a0f9"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "08590d4912ce34fcbd22db6e5fb76a4a8e6de82daa19053104383c900a47f404"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.aarch64-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce20e67c64ed4dba9c32798f299a3715e8cca1cd"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "df7dc5167906693713118738e18e8f60a919b68222e0f8864f122c93e2a4c8c7"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.aarch64-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "aarch64"
git-tree-sha1 = "77ce26fd93bd8dd96d1b6f2e7cf476d2080ef1fc"
os = "freebsd"

    [[libaom.download]]
    sha256 = "737a0e6947075740fb48b18421670cadeea83af742a25e92ba667fe64dac2e98"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.aarch64-unknown-freebsd.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5ffb540be3db4a790bf8781f9c004c7743f0a25"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "500d93fbf152584eda1b1c2678ba371ffada5643d8620bc461b61f6f0e8bca62"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2746659d8ca402cedb72f9647effa03feac5339b"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "f7196cdcfd390124a153cff1de126bc6ae912231e7185b03e0fa6cad0363cc32"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5db34d241265836a213616dda046e77f60510541"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "d2fb4e7e94037d7d286dfd0508961246ce964aec03353c897d73b7e45dbf03b2"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libaom]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e64fecd96f07c02dfe9bc7662ea2dce50d54795e"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "9da76cf2c9921d8810cfae0ef3919f89da37e0a047b125107dc2662f8af9fb0a"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c3e80bb3b6c2568b334558bd1b6cc47bd95e894"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "68a2da5152ba8c9a043cdc998f50b21985c45c3fa352a499cf113483d448458d"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.i686-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bc7f7dda85e360c63b5e3dc5a7f20386bb182a56"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "0dd95dc8e3b055c287c845edfc4d0b8e3a951bb3cd2a9abb64f533ee26041bb3"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.i686-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ddf635756ce2fddd8b68d7846315f5c476d336ef"
os = "windows"

    [[libaom.download]]
    sha256 = "12124265fd2fc694bd4d8e2732ff4c76a944c9f0c6c2d79fc10bfcce92858e2b"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.i686-w64-mingw32-cxx11.tar.gz"
[[libaom]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e44567dbe36bdd05366582af624141eb1088041"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "8b7c1aa8e8cf07903239a45505bd080cef23ad38017ce25fc4da7ff3ca82f798"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c731b003ef4d87d792c5739f0504b5928d839ad6"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "f469f63802c88b7c9c044a4c8d639ff5f6810ae59620dae986b7d4a677c09cbe"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.riscv64-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
git-tree-sha1 = "2ab4c11fdae101750bd24a00db4abb1da55e775e"
os = "macos"

    [[libaom.download]]
    sha256 = "aa2537dcbad6cf0103d156a736a346a3f48625a5b81f45127d786a0dc8584226"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.x86_64-apple-darwin.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9e1fda792c62e2d42bc46bbd59bea3aafc2c2a6"
libc = "glibc"
os = "linux"

    [[libaom.download]]
    sha256 = "309639309b8520ca9a871b41543827808870ff569aecb8b986df94ce827db071"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.x86_64-linux-gnu-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "82e21c26ec4132f3d7c61a1925a551550f282a2b"
libc = "musl"
os = "linux"

    [[libaom.download]]
    sha256 = "8d26c103db4f41c5af028be74979fc69ef9ce058e2d38ee7e50713bd63463f66"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.x86_64-linux-musl-cxx11.tar.gz"
[[libaom]]
arch = "x86_64"
git-tree-sha1 = "1ecfbd06dc16913ca825908a18f6c4c6132b45eb"
os = "freebsd"

    [[libaom.download]]
    sha256 = "838260d0d2e266e48071da0fe27e34b0a22efd03b3bff56e0470b5b1cb3e2806"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.x86_64-unknown-freebsd.tar.gz"
[[libaom]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67a1b28b0dfce7148d71b3a283573c7799e66724"
os = "windows"

    [[libaom.download]]
    sha256 = "c3d8914ee37ba564b0eeda711208e78844732ec015f7575c674912f1dbef92b7"
    url = "https://github.com/JuliaBinaryWrappers/libaom_jll.jl/releases/download/libaom-v3.15.1+0/libaom.v3.15.1.x86_64-w64-mingw32-cxx11.tar.gz"
